  development:
    adapter: postgresql
    encoding: unicode
    database: UTU_development
    pool: 5
    username: postgres
    password: danjegay

  test:
    adapter: postgresql
    encoding: unicode
    database: UTU_test
    pool: 5
    username: postgres
    password: danjegay
